In [126]:
import numpy as np # type: ignore
import matplotlib.pyplot as plt # type: ignore
import pandas as pd # type: ignore
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # type: ignore
from sklearn.compose import ColumnTransformer # type: ignore
from sklearn.model_selection import train_test_split # type: ignore
from sklearn.preprocessing import StandardScaler # type: ignore
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import Dense # type: ignore
from sklearn.model_selection import train_test_split # type: ignore
import pandas as pd # type: ignore
from sklearn.metrics import classification_report # type: ignore

In [127]:
dataset = pd.read_csv('Obesity Classification.csv')

In [128]:
dataset['BMI'] = round(dataset['BMI']).astype(int)

In [129]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      108 non-null    int64 
 1   Age     108 non-null    int64 
 2   Gender  108 non-null    object
 3   Height  108 non-null    int64 
 4   Weight  108 non-null    int64 
 5   BMI     108 non-null    int32 
 6   Label   108 non-null    object
dtypes: int32(1), int64(4), object(2)
memory usage: 5.6+ KB


In [130]:
X = dataset.iloc[:, 3:6].values
y = dataset.iloc[:, 6].values

In [131]:
dataset.head()

ID  Age  Gender  Height  Weight  BMI          Label
0   1   25    Male     175      80   25  Normal Weight
1   2   30  Female     160      60   22  Normal Weight
2   3   35    Male     180      90   27     Overweight
3   4   40  Female     150      50   20    Underweight
4   5   45    Male     190     100   31          Obese

In [132]:
X

array([[175,  80,  25],
       [160,  60,  22],
       [180,  90,  27],
       [150,  50,  20],
       [190, 100,  31],
       [140,  40,  17],
       [200, 110,  34],
       [130,  30,  13],
       [210, 120,  37],
       [120,  20,  10],
       [175,  70,  23],
       [160,  50,  20],
       [180,  80,  25],
       [150,  60,  22],
       [190,  90,  27],
       [140,  50,  20],
       [200, 100,  31],
       [130,  40,  17],
       [210, 110,  34],
       [120,  30,  13],
       [175,  80,  25],
       [160,  60,  22],
       [180,  90,  27],
       [150,  50,  20],
       [190, 100,  31],
       [140,  40,  17],
       [200, 110,  34],
       [130,  30,  13],
       [210, 120,  37],
       [175,  75,  24],
       [160,  55,  21],
       [180,  85,  26],
       [190,  95,  27],
       [140,  75,  25],
       [200, 105,  29],
       [130,  85,  28],
       [210, 115,  31],
       [120,  95,  29],
       [175,  65,  23],
       [160,  45,  19],
       [180,  75,  24],
       [150,  55

In [133]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

print(y)

[0 0 2 3 1 3 1 3 1 3 0 3 0 0 2 3 1 3 1 3 0 0 2 3 1 3 1 3 1 0 0 2 2 2 1 2 1
 2 0 3 0 0 2 0 2 2 1 2 0 3 0 0 2 0 2 2 1 2 0 3 0 3 0 0 2 0 2 2 3 3 0 3 0 3
 0 0 2 0 3 3 3 3 0 3 3 3 3 3 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [134]:
# Membagi data ke test dan training set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [135]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [137]:
# Inisialisasi ANN
MesinKlasifikasi = Sequential()

# Menambah input layer dan hidden layer pertama
MesinKlasifikasi.add(Dense(units=12, kernel_initializer='uniform', activation='relu', input_dim=3))

# Menambah hidden layer kedua
MesinKlasifikasi.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

# Menambah output layer dengan activation='softmax' untuk klasifikasi multi-kelas
MesinKlasifikasi.add(Dense(units=4, kernel_initializer='uniform', activation='softmax'))

# Compile model dengan loss='sparse_categorical_crossentropy' untuk klasifikasi multi-kelas
MesinKlasifikasi.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Fitting ANN ke training set
history = MesinKlasifikasi.fit(X_train, y_train, batch_size=10, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
8/8 [==============================] - 1s 34ms/step - loss: 1.3849 - accuracy: 0.4933 - val_loss: 1.3843 - val_accuracy: 0.4242
Epoch 2/100
8/8 [==============================] - 0s 10ms/step - loss: 1.3818 - accuracy: 0.4400 - val_loss: 1.3821 - val_accuracy: 0.4242
Epoch 3/100
8/8 [==============================] - 0s 8ms/step - loss: 1.3783 - accuracy: 0.4400 - val_loss: 1.3800 - val_accuracy: 0.4242
Epoch 4/100
8/8 [==============================] - 0s 9ms/step - loss: 1.3746 - accuracy: 0.4400 - val_loss: 1.3774 - val_accuracy: 0.4242
Epoch 5/100
8/8 [==============================] - 0s 9ms/step - loss: 1.3705 - accuracy: 0.4400 - val_loss: 1.3744 - val_accuracy: 0.4242
Epoch 6/100
8/8 [==============================] - 0s 8ms/step - loss: 1.3657 - accuracy: 0.4400 - val_loss: 1.3703 - val_accuracy: 0.4242
Epoch 7/100
8/8 [==============================] - 0s 8ms/step - loss: 1.3598 - accuracy: 0.4400 - val_loss: 1.3654 - val_accuracy: 0.4242
Epoch 8/100
8/8 [========

In [138]:
# Melakukan prediksi pada set pengujian
y_pred = MesinKlasifikasi.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Mengonversi label yang sudah diencode kembali ke label aslinya
y_test_orig = label_encoder.inverse_transform(y_test)
y_pred_orig = label_encoder.inverse_transform(y_pred_classes)

# Mencetak confusion matrix
cm = confusion_matrix(y_test_orig, y_pred_orig)
print("Confusion Matrix:")
print(cm)

2/2 [==============================] - 0s 2ms/step
Confusion Matrix:
[[ 6  0  0  0]
 [ 0  0  5  0]
 [ 4  0  4  0]
 [ 0  0  0 14]]


In [139]:
# Melakukan prediksi pada data test
y_pred_test = MesinKlasifikasi.predict(X_test)
y_pred_classes_test = np.argmax(y_pred_test, axis=1)

# Mengonversi label yang sudah diencode kembali ke label aslinya untuk data test
y_test_orig = label_encoder.inverse_transform(y_test)
y_pred_orig_test = label_encoder.inverse_transform(y_pred_classes_test)

# Membuat classification report untuk data test
report_test = classification_report(y_test_orig, y_pred_orig_test, output_dict=True)

# Mengonversi classification report ke dalam bentuk DataFrame
df_report_test = pd.DataFrame(report_test).transpose()

# Mencetak classification report untuk data test
print("Classification Report for Test Data:")
print(df_report_test)

2/2 [==============================] - 0s 2ms/step
Classification Report for Test Data:
               precision    recall  f1-score    support
Normal Weight   0.600000  1.000000  0.750000   6.000000
Obese           0.000000  0.000000  0.000000   5.000000
Overweight      0.444444  0.500000  0.470588   8.000000
Underweight     1.000000  1.000000  1.000000  14.000000
accuracy        0.727273  0.727273  0.727273   0.727273
macro avg       0.511111  0.625000  0.555147  33.000000
weighted avg    0.641077  0.727273  0.674688  33.000000


c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [140]:
# Mencetak label asli dan prediksi untuk setiap sampel
print("\nLabel Asli dan Prediksi untuk Setiap Sampel:")
for i in range(len(X_test)):
    print("Data ke-", i+1)
    print("Label Asli:", y_test_orig[i])
    print("Prediksi:", y_pred_orig[i])
    print()



Label Asli dan Prediksi untuk Setiap Sampel:
Data ke- 1
Label Asli: Underweight
Prediksi: Underweight

Data ke- 2
Label Asli: Normal Weight
Prediksi: Normal Weight

Data ke- 3
Label Asli: Normal Weight
Prediksi: Normal Weight

Data ke- 4
Label Asli: Overweight
Prediksi: Overweight

Data ke- 5
Label Asli: Obese
Prediksi: Overweight

Data ke- 6
Label Asli: Underweight
Prediksi: Underweight

Data ke- 7
Label Asli: Underweight
Prediksi: Underweight

Data ke- 8
Label Asli: Underweight
Prediksi: Underweight

Data ke- 9
Label Asli: Obese
Prediksi: Overweight

Data ke- 10
Label Asli: Underweight
Prediksi: Underweight

Data ke- 11
Label Asli: Underweight
Prediksi: Underweight

Data ke- 12
Label Asli: Overweight
Prediksi: Overweight

Data ke- 13
Label Asli: Overweight
Prediksi: Normal Weight

Data ke- 14
Label Asli: Normal Weight
Prediksi: Normal Weight

Data ke- 15
Label Asli: Overweight
Prediksi: Normal Weight

Data ke- 16
Label Asli: Overweight
Prediksi: Normal Weight

Data ke- 17
Label Asli

In [118]:
# Melakukan prediksi pada seluruh data
y_pred_all = MesinKlasifikasi.predict(X)
y_pred_classes_all = np.argmax(y_pred_all, axis=1)

# Mengonversi label yang sudah diencode kembali ke label aslinya
y_orig = label_encoder.inverse_transform(y)

# Mengonversi label prediksi yang sudah diencode kembali ke label aslinya
y_pred_orig_all = label_encoder.inverse_transform(y_pred_classes_all)

# Mencetak confusion matrix
cm = confusion_matrix(y_orig, y_pred_orig_all)
print("Confusion Matrix:")
print(cm)

4/4 [==============================] - 0s 2ms/step
Confusion Matrix:
[[23  1  1  4]
 [ 0  9  3  0]
 [ 6  8  6  0]
 [ 4  0  0 43]]
